//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Infrastructure.Hosting.Common.RabbitMQ {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Infrastructure.Hosting.Common.RabbitMQ.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A connection string for RabbitMQ is missing.
        /// </summary>
        internal static string RabbitMQStore_MissingConnectionString {
            get {
                return ResourceManager.GetString("RabbitMQStore_MissingConnectionString", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A queue name is missing.
        /// </summary>
        internal static string RabbitMQStore_MissingQueueName {
            get {
                return ResourceManager.GetString("RabbitMQStore_MissingQueueName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A topic name is missing.
        /// </summary>
        internal static string RabbitMQStore_MissingTopicName {
            get {
                return ResourceManager.GetString("RabbitMQStore_MissingTopicName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A subscription name is missing.
        /// </summary>
        internal static string RabbitMQStore_MissingSubscriptionName {
            get {
                return ResourceManager.GetString("RabbitMQStore_MissingSubscriptionName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A message is missing.
        /// </summary>
        internal static string RabbitMQStore_MissingMessage {
            get {
                return ResourceManager.GetString("RabbitMQStore_MissingMessage", resourceCulture);
            }
        }
    }
}
